name: Evaluate
description: |
    A github action for running evaluations in CI.
inputs:
    data:
      required: true
    ai_model_configuration:
      required: true
    evaluators:
      required: true
    evaluation_name:
      required: false
      default: null
    evaluator_config:
      required: false
      default: null
    azure_ai_project:
      required: false
      default: null
outputs:
    results:
      description: The evaluation results. Results are returned in jsonl format
      value: ${{ steps.run-evaluation.outputs.results }}
    summary:
      description: The evaluation summary, rendered as a markdown file.
      value: ${{ steps.run-evaluation.outputs.summary }}
runs:
    using: "composite"
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          : pip install "${{ github.action_path }}"
          echo "::group::pip install"
          pip install "${{ github.action_path }}"
          echo "::endgroup::"
        shell: bash
      - name: Generate Config
        run: |
          cat > ${{ github.action_path }}/config.json << EOF
            {
              "data": ${{ toJSON(inputs.data) }},
              "ai_model_configuration": ${{ toJSON(fromJSON(inputs.ai_model_configuration)) }},
              "evaluators": ${{ toJSON(fromJSON(inputs.evaluators)) }},
              "evaluation_name": ${{ inputs.evaluation_name && toJSON(fromJSON(inputs.evaluation_name)) || 'null' }},
              "evaluator_config": ${{ inputs.evaluator_config && toJSON(fromJSON(inputs.evaluator_config)) || 'null' }},
              "azure_ai_project": ${{ inputs.azure_ai_project && toJSON(fromJSON(inputs.azure_ai_project)) || 'null' }},
              "output_path": "${{ github.action_path }}/results.jsonl"
            }
          EOF
        shell: bash
      - name: Run Evaluation
        id: run-evaluation
        run: |
          python -m ai_evaluate_action --config ${{ github.action_path }}/config.json --summary "${{ github.action_path }}/summary.md"
          {
            echo 'results<<EOF'
            cat "${{ github.action_path }}/results.jsonl"
            echo ""
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          {
            echo 'summary<<EOF'
            cat "${{ github.action_path }}/summary.md"
            echo ""
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
        shell: bash
