name: Run Tests

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/test-*'
      - '.github/workflows/run-tests.yaml'
  workflow_dispatch:

jobs:
  test-evaluate:
    uses: ./.github/workflows/test-ai-evaluation.yaml
    secrets: inherit
